version: '3.8'
services:
  mysql:
    image: mysql:8
    command: --secure-file-priv=""
    restart: always
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jwt_security
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - /home/monteiro:/home/monteiro

volumes:
  mysql_data: